### PR TITLE
Updates crontab to 1.01 and includes new maintainer

### PR DESCRIPTION
**Pull request by sanurielf**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Closes #12 , #10 , #9 #8

### CODE REVIEW

**Comment by sanurielf** [comment]
Hey @h-vetinari PR is ready for review. Thanks for your support!

**Comment by h-vetinari** [comment]
@conda-forge-admin, please rerender

**Review by h-vetinari — APPROVED** [review]
This looks good to me, thank you!

The one thing I would recommend to do going forward, is to have separate commits for changes to the recipe on the one hand, and changes to the feedstock infrastructure (i.e. what the bot rerender does) on the other. For example 6787653ed84be29d210c126ce82e5af62cdc4395 is misleadingly titled, as it hides the whole feedstock rerender after a long period of inaction.

**Comment by sanurielf** [comment]
Awesome! thanks for the feedback @h-vetinari !

**Pull request merged**
